[package]
name = "data-rw"
version = "0.1.6"
authors = ["luyi <luyikk@126.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/luyikk/buffer"
documentation = "https://docs.rs/buffer"
description = "io buffer write reader."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes="0.6"
paste="1.0.2"